# Generated by Django 4.1.7 on 2023-02-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='email',
            field=models.EmailField(default='User@sample', max_length=254),
        ),
    ]
